### ISSUE TITLE
Catalan Language in version 0.8.11.8 does not work

### ISSUE THREAD

**Issue by epertinez** [tgalal/wazapp#154]
I try to set the language to catalan in  0.8.11.8 but it doesn't work.

I restarted the phone just to be sure wazzapp restarted, but without success. I tried with Spanish without success neither.

Anyway, thanks for your incredible work.

**Comment by ghost** [comment]
Please try this:
http://talk.maemo.org/showpost.php?p=1277303&postcount=5714

Explanation:
Development versions do not contain languages, so you have to download them from Transifex, compile them and put them in the i18n folder yourself. The above script takes care of that.

**Comment by epertinez** [comment]
Perfetc. It worked. Thanks. I had to change to english and then back to catalan for the patch to work.

**Comment by ghost** [comment]
Nice!
Changing language is required because current language is stored in "~/.wazapp/language.qm". I could delete that file every time you re-run the language update script but then language would be english and that could lead to confusion. So every time you update the language pack with the script, you change your language to english then just change back to the language you want and then restart Wazapp.
