### ISSUE TITLE
Reevaluate and restructure Emoji adding UI

### ISSUE THREAD

**Issue by MoritzJT** [tgalal/wazapp#175]
Concerning the recently used Emoji tab. I suggest we change the current behaviour of the Emoji button to opening a overlay popup similar to the one for attachments. This popup will always contain a button to open all Emoji but will continue to fill up with recently used Emoji either enlarging the popup to the top, or having them sidescrollable. On another note one could think about using a method to define favourites rather than autoadding recent Emoji.

This way we'd have a much less intrusive and fast option to insert Emoji with a shorter blend time and less to load in QML and also I'd suggest that on long press Emoji not only the Emoji is inserted but also a Space behind it! The Popup could show Emoji a little larger so it's easier to insert the last used ones.

**Comment by CODeRUS** [comment]
we can add loading all emoji to the memory while app loading. it took about 10-15 seconds, i think. and will be no lag in using emoji dialog.
but i'm not sure about power usage and memory after this operation.

**Comment by tgalal** [comment]
First time you open emoji dialog, there is a lag for each tab only once. Because and emoji section gets loaded into memory on first demand, and then subsequent requests are immediate. And I don't want to add more time in startup, 15 seconds is too long.

Recent Emoji has purpose, which is showing recently used Emoji. Favorites is a totally different thing.
