### ISSUE TITLE
Parse expiration problem

### ISSUE THREAD

**Issue by tgalal** [tgalal/wazapp#237]
File "/opt/waxmppplugin/bin/wazapp/wazapp", line 51, in <module>
wam = WAManager(app)
File "/opt/waxmppplugin/bin/wazapp/wamanager.py", line 51, in **init**
self.proceed()
File "/opt/waxmppplugin/bin/wazapp/wamanager.py", line 129, in proceed
account = AccountsManager.getCurrentAccount();
File "/opt/waxmppplugin/bin/wazapp/accountsmanager.py", line 34, in getCurrentAccount
account = AccountsManager.findAccount()
File "/opt/waxmppplugin/bin/wazapp/accountsmanager.py", line 87, in findAccount
account.valueAsString("price_expiration"))
File "/opt/waxmppplugin/bin/wazapp/Models/account.py", line 51, in setExtraData
self.expiration = int(expiration)
ValueError: invalid literal for int() with base 10: ''

**Comment by mudspot** [comment]
Hi,

I'm the OP for the above post.

I did some trace. Somehow, it turns out that my expiration is an empty string.

I don't know if this is a correct hack. I got mine working by setting expiration to = price_expiration if expiration==""
I did this in Model/account.py

def setExtraData(self, kind, expiration, cost, currency, price, price_expiration):
                self.kind = kind
-              if expiration=="":
-                       expiration = price_expiration
              self.expiration = int(expiration)
              self.cost = cost
              self.currency = currency
              self.price = price
              self.price_expiration = price_expiration

**Comment by CODeRUS** [comment]
i don't think its good hack.
my way:

try:
        self.expiration = int(expiration)
except:
        continue

**Comment by mudspot** [comment]
I wasn't familiar with the code base. So I assumed that a non-0 value of expiration is needed, hence my assignment of expiration=price_expiration

There was a TODO note to set expiration = creation date if expiration is empty. That's why I thought non-empty expiration is needed.

PS. Installing your nightly build you sent.
PPS. Your nightly10 is all good. The above issue is no longer encountered.
