### ISSUE TITLE
wazapp stays online forever

### ISSUE THREAD

**Issue by babooo** [tgalal/wazapp#253]
wazapp stays online even after you close it

**Comment by CODeRUS** [comment]
swipe down doesnt close application, it's feature.
use menu Quit item

**Comment by babooo** [comment]
Yes I do know that when you swipe down it stays connected, what I meant is that I still appear online to all my friends even when I swipe down which was not the case in previous versions.this happens with me randomly and not always

**Comment by CODeRUS** [comment]
@tgalal maybe need to wait while lastseen signal will be sent?

**Comment by babooo** [comment]
I waited for more than 24 hours, I uninstalled it then reinstalled it for it to work

**Comment by tgalal** [comment]
@CODeRUS lastseen is sent 5 seconds after the app loses focus, we can't wait for that :), besides there is no receipt for it, so we could never actually know if it was successfully sent. However, there is no reason for it to not go out unless connection was lost, otherwise it has always worked fine with me. But anyway it seems to be working again with @babooo and no one else has reported it.

@babooo thanks for reporting this, I'll keep an eye on it
