### ISSUE TITLE
Wazapp does not send files

### ISSUE THREAD

**Issue by alinanurumova** [tgalal/wazapp#263]
Can you help me,please? Recently I downloaded wazapp and everything was normal. After a while it does not send the files (pictures, music, ...) what can be done to correct the error? and I have wazapp on nokia n9)

**Comment by susha987** [comment]
The same problem!!!I reported my problem a few days ago,but it still there,so sad:(

**Comment by Lindskj** [comment]
Same problem here, worked before but not anymore.. N9 PR1.3  Dev mode enabled.

**Comment by jemaya** [comment]
Same problem since one week

**Comment by alinanurumova** [comment]
Pip) if you adjust that problem, can u tell me, pleaaaase( for me wazapp without sending files not interesting:(

**Comment by PiroMaster** [comment]
Same problem with me since 3 days.
It suddenly stopped sending files. It just says initializing the whole time.

**Comment by alinanurumova** [comment]
yeah, the same) just says initializing:( Pip, who can help???

**Comment by knobtviker** [comment]
What is wrong with you people?
So many times we have said that we are aware of it and that we are working on a solution. 
Why do you constantly bother us with emails that are made of your despair crying out for help???

Read the following paragraph very carefully until you really understand every word:
This is not a forum or a chat.
This issue has been reported.
We are working on a solution as fast as our human lives allow.
Do not chat here or spam.
Post here only if you have a solution.
Otherwise GTFO.

Has this been clear and direct enough?

With every single following post, I'll personally delay the release once it's done for 1 post = 1 day delay.
Your choice.
Thank you.

**Comment by alinanurumova** [comment]
But at the beginning it worked good) what's wrong??/arrrr

**Comment by tgalal** [comment]
duplicate #259

**Comment by Alkabten77** [comment]
Dear T galal,

i tray to get fix update but its not downlod

**Comment by susha987** [comment]
also tried to do it but its not download

**Comment by susha987** [comment]
Everything working perfect now,i downloaded new version 0.9.20,thx guys a lots.Well done!!!!
