### ISSUE TITLE
Installation interrupted 

### ISSUE THREAD

**Issue by Oveka** [tgalal/wazapp#266]
I recently deletewazapp due to the file sending issies to see if
re installing would fix the issue. Now everytime iv tried to install wazapp after downloading it on my nokia n9 i keep getting installation interrupted try again or cancel. I keep trying but have the same issue. Please advise if i have to wait till new version??

**Comment by thom45** [comment]
I made the same mistake, uninstalled Wazapp and then attempted a clean install of 0.9.19. When I accept to download additional dependencies I get the message Installation failed, installation interrupted. Have been trying for three days, to no avail.

**Comment by CODeRUS** [comment]
you should do installation from terminal and show the log. othervise no help.

**Comment by thom45** [comment]
I have never used the terminal. I have used maemo devices since the Nokia 770, but I am a 'normal' user. Only ended up on GitHub because I was trying to find some help and let you know about this issue. If this is not only my problem, it would mean that at the moment new users cannot install Wazapp on their N9 unless they use the terminal. I appreciate that might be a minority as the N9 is such a specialist device.

I think you have done a brilliant job with this app, that is why I am gutted that I cannot get it to work again. Thanks

Thomas Manss & Company Limited
3 Nile Street
London N1 7LX
T +44 20 7251 7777
F +44 20 7251 7778
skype: thomasmanss  
www.manss.com
twitter.com/thomasmanss
facebook.com/thomasmanss

**Comment by Oveka** [comment]
I actually set my phone back to its factory settings. I know it sounds extreme, but it installed without issues after i.did this You could.save your files on a pc..im glad iv got it working. Its a great app. Thanks tgalal and team.

Date: Sat, 13 Apr 2013 23:01:20 -0700

**Comment by thom45** [comment]
No luck with the reset, the installation still fails

Thomas Manss & Company Limited
3 Nile Street
London N1 7LX
T +44 20 7251 7777
F +44 20 7251 7778
skype: thomasmanss  
www.manss.com
twitter.com/thomasmanss
facebook.com/thomasmanss

**Comment by thom45** [comment]
A complete purge of wazapp from the terminal and subsequent reinstall of 0.9.19 fixed this, thanks for your help
