### ISSUE TITLE
wazapp triggering annoying "connect to internet" dialogs.

### ISSUE THREAD

**Issue by mkulke** [tgalal/wazapp#59]
i am not sure wether this is an issue or if there is a way to work around this, it can be quite annoying in certain situations anyway. i was in a foreign country and thus turned off my data services on the phone. wazapp was running in the background (not visible in open apps view) and constantly interrupting the display of the navigation app while driving a car. it took me a while to figure out, that wazapp was running in the background and attempting to connect periodically. when i reopened wazapp and quit it via the menu the annoying dialogs disappeared. 

maybe this behaviour is intended (e.g. in case you forget to activate an internet connection and wait for wazapp messages to arrive), but the other background services like skype or gtalk do not behave this way when there is no internet connection.

**Comment by tgalal** [comment]
Many people requested auto connect. And that dialog is the default N9 behavior when wazapp tries to connect, with autoconnect disabled in phone settings. But if you compare this to skype/gtalk, whatsapp's goal is to replace SMS to a high extent. To achieve that it must keep an always connected state. That's why in some platforms original client doesn't even allow you to quit. So on N9 as you said, to stop it you need to use the extra luxury quit button which is not available in other platforms :)

**Comment by RobertMe** [comment]
Instead of just trying to reconnect you could use the [QNetworkConfigurationManager](http://harmattan-dev.nokia.com/docs/library/html/qt4/qnetworkconfigurationmanager.html). It reports whether the device is online or not. So if the connection goes offline you could just wait till it comes back online and then open a new QNetworkSession. This way the user doesn't get nagged to connect to the internet every X minutes. It's the users choice to disable the internet connection and the app doesn't have to nag the user with it. When the user sets the device in flight mode the device also doesn't keep nagging the user about getting the device out of flight mode so it could possibly receive SMS messages.

(again, if you could provide some details about how to setup a development environment I might try to implement this myself and send in a pull request)

**Comment by tgalal** [comment]
If a user doesn't want to be nagged, just quits the app. If you do want to contribute, you can modify and copy the python files to device  (/opt/waxmppplugin/bin/wazapp/) and run it (python /opt/waxmppplugin/bin/wazapp/wazapp). Or setup a scratchbox env, (you can google that for harmattan). However, you should know that the change you are suggesting is not going to be pulled in.

**Comment by mkulke** [comment]
Maybe a compromise could be making the wazapp app visible when it is hidden and demanding a connection, so users know what is issueing the connection dialog. like i said, i was screaming at my poor n9 for a while, as i did not figure out what was those causing connection requests.

**Comment by RobertMe** [comment]
Or automatically reconnect when the connection comes back online, and request an active connection when opening the main window. But this still has the problem of not being able to receive messages when offline. But I still think it should be the users choice to disable the internet connection (to prevent roaming, increase battery duration), or the user could simply be out of range of a 3G and WIFI network.

This is also how the default IM plugins and email act. When the connection drops they go offline and stay offline. When the connection comes back online they automatically log in again (or restart the email checking schedule).

**Comment by tgalal** [comment]
@mkulke I agree with your suggestion.

**Comment by calvaris** [comment]
I think @RobertMe is right and the best idea is bringing the connection dialog (active connection) only when the application is being opened (or brought to foreground) and using background connections for the rest of cases. You already know that you are not going to receive messages if you are not online and that's why the device has the automatic and manual connections. Doing it other way distorts a bit that idea.
